# Generated by Django 6.0.6 on 2026-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('niche', models.CharField(blank=True, default='', max_length=120)),
                ('result', models.TextField(blank=True, default='', help_text='Короткая строка результата или описания (произвольный текст)')),
                ('link', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Ссылка на YouTube в любом формате (watch?v=…, youtu.be/…, /shorts/…)', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рилс',
                'verbose_name_plural': 'Рилсы',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
