# Generated by Django 6.0.6 on 2026-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Основной текст «о компании» — показывается в модалке на сайте'),
        ),
    ]
