# Generated by Django 6.0.6 on 2026-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vacancy_age_max_vacancy_age_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметка «в топ» — попадает в подборку топ-кейсов на странице /smm'),
        ),
    ]
