# Generated by Django 6.0.6 on 2026-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_description',
            field=models.TextField(blank=True, default='', help_text='Развёрнутое описание для страницы кейса'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, help_text='Скриншот для мокапа на карточке и в кейсе', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на живой сайт проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Стабильный id для маршрута кейса; пусто → авто из названия', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Короткое описание для карточки'),
        ),
    ]
