# Generated by Django 6.0.6 on 2026-06-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_project_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Разработка', 'Разработка'), ('SMM', 'SMM'), ('Дизайн', 'Дизайн'), ('Реклама', 'Реклама')], max_length=20),
        ),
    ]
