# Generated by Django 6.0.6 on 2026-06-16 11:57

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, help_text='Файл ТЗ из формы брифа (приватное хранилище, как у резюме)', null=True, storage=apps.leads.models.select_resume_storage, upload_to=apps.leads.models.brief_upload_path),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Видимое название компании из формы брифа (не honeypot)', max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Необязательное сообщение / текст брифа'),
        ),
    ]
