# Generated by Django 6.0.6 on 2026-06-11 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('slug', models.SlugField(help_text='Стабильный id в URL: /news/<slug>', max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('excerpt', models.CharField(help_text='Короткое описание для карточки и превью (1–2 предложения).', max_length=300)),
                ('body', models.TextField(help_text='Текст статьи (HTML).')),
                ('cover', models.ImageField(blank=True, help_text='Обложка (опц.). Публичное хранилище, как у логотипов.', null=True, upload_to='news/')),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO <title> (пусто → берётся title).', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', help_text='SEO meta description (пусто → берётся excerpt).', max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Ключевые слова (список) для meta keywords.')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата публикации (используется для сортировки ленты).')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ручная сортировка (меньше — выше). При равенстве — новее выше.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['sort_order', '-published_at', '-created_at'],
            },
        ),
    ]
